/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.0.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

dependencyResolutionManagement {
  // Use Maven Central as the default repository (where Gradle will download dependencies) in all subprojects.
  @Suppress("UnstableApiUsage")
  repositories {
    mavenCentral()
    maven { url = uri("https://repo.spring.io/milestone") }
    maven { url = uri("https://repo.spring.io/snapshot") }
    maven { url = uri("https://packages.confluent.io/maven/") }
    mavenLocal()
  }
}

pluginManagement {
  repositories {
    gradlePluginPortal()
    mavenCentral()
    mavenLocal()
  }
}

enableFeaturePreview("STABLE_CONFIGURATION_CACHE")

rootProject.name = "oss"

include(":grpc-contract-packager")
include(":grpc-contract-compiler")
include(":examples:grpc-contract")